name = "kRPC"
uuid = "1c1c9389-3631-468f-a056-497e06f4ffdb"
authors = ["Ben Chung <ckfinite@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
