name = "kRPC"
uuid = "1c1c9389-3631-468f-a056-497e06f4ffdb"
authors = ["Ben Chung <ckfinite@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
